#!/usr/bin/env python3

emoji_rules = [
    (["baguette"], "🥖"),
    (["donut", "doughnut"], "🥯"),
    (["pancake", "crepe"], "🥞"),
    (["hot dog", "saveloy", "frankfurter"], "🌭"),
    (["burger", "big mac", "whopper"], "🍔"),
    (["fries", "chips", "wedges"], "🍟"),
    (["noodle", "ramen", "stir fry"], "🍜"),
    (["spaghetti", "bolognese", "pasta"], "🍝"),
    (["dumpling", "gyoza", "pasty", "fritter"], "🥟"),
    (["sandwich"], "🥪"),
    (["pizza", "calzone"], "🍕"),
    (["waffle"], "🧇"),
    (["taco", "fajita", "fahita"], "🌮"),
    (["burrito", "wrap", "kebab", "chapati", "roti", "tortilla"], "🌯"),
    (["falafel"], "🧆"),
    (["paella"], "🥘"),
    (["salad"], "🥗"),
    (["potato"], "🥔"),
    (["pot"], "🍲"),
    (["popcorn"], "🍿"),
    (["sushi"], "🍙"),
    (["rice"], "🍚"),
    (["curry"], "🍛"),
    (["crab"], "🦀"),
    (["lobster"], "🦞"),
    (["langoustine"], "🦐"),
    (["octopus", "squid", "calamari"], "🦑"),
    (["ice cream"], "🍦"),
    (["cookie"], "🍪"),
    (["cake", "bun"], "🍰"),
    (["pie", "quiche", "sausage roll"], "🥧"),
    (["pastry"], "🥐"),
    (["chocolate", "cocoa"], "🍫"),
    (["honey"], "🍯"),
    (["coffee", "espresso"], "☕"),
    ([
        "ham",
        "leg",
        "lamb",
        "veal",
        "venison",
        "gammon",
        "sausage"
    ], "🍖"),
    (["bacon", "pork"], "🥓"),
    (["chicken", "drumstick", "duck", "turkey"], "🍗"),
    (["crumpet"], "🍞"),
    (["beef", "steak", "rump", "sirloin"], "🥩"),
    (["shrimp", "prawn"], "🍤"),
    (["green bean"], "🫛"),
    (["bean", "dahl", "gram", "lentils"], "🫘"),
    (["fortified"], "🏰"),
    (["coconut"], "🥥"),
    ([
        "nut",
        "acorn",
        "almond",
        "walnut",
        "betel",
        "cashew",
        "dika",
        "kola",
        "macadamia",
        "pecan",
        "pistachio",
        "water caltrop",
    ], "🥜"),
    (["grape", "blackberry", "blackberries", "blackcurrant"], "🍇"),
    (["watermelon"], "🍉"),
    (["melon"], "🍈"),
    (["orange"], "🍊"),
    (["lemon", "lime"], "🍋"),
    (["banana"], "🍌"),
    (["pineapple"], "🍍"),
    (["peach", "apricot", "plum", "pomegranate"], "🍑"),
    (["cherry", "cherries"], "🍒"),
    (["strawberry", "strawberries"], "🍓"),
    (["blueberry", "blueberries"], "🫐"),
    (["kiwi"], "🥝"),
    (["turnip", "beetroot", "fig"], "🌰"),
    (["biscuit"], "🍪"),
    (["berry", "berries"], "🫒"),
    (["avacado"], "🥑"),
    (["aubergine", "eggplant", "baigan", "brinjal"], "🍆"),
    (["potato", "aloo", "mash"], "🥔"),
    (["carrot"], "🥕"),
    (["corn"], "🌽"),
    (["chilli", "spice", "pepper"], "🌶️"),
    ([
        "cucumber",
        "gherkin",
        "okra",
        "pickle",
        "zucchini",
        "courgette",
    ], "🥒"),
    ([
        "lettuce",
        "leaf",
        "artichoke"
        "spinach",
        "spinach",
        "cabbage",
        "choy",
        "celeriac",
        "basil",
        "coriander",
        "leaves",
        "fennel",
    ], "🥬"),
    ([
        "broccoli",
        "artichoke",
        "veg",
        "kale",
        "sorouts",
        "green beans",
        "asparagus",
        "celery",
        "arugula",
        "cauliflower",
        "chard",
    ], "🥦"),
    (["garlic"], "🧄"),
    (["onion"], "🧅"),
    (["tomato"], "🍅"),
    (["ginger"], "🫚"),
    (["wheat", "barley", "grain", "oat"], "🌾"),
    (["pea", "edamame", "soya"], "🫛"),
    (["mushroom"], "🍄"),
    (["egg"], "🍳"),
    (["bread", "bagel", "crumpet", "naan", "pitta"], "🍞"),
    (["cheese"], "🧀"),
    (["apple", "fruit"], "🍎"),
    (["sprout", "herb"], "🌱"),
    (["pumpkin"], "🎃"),
    (["tin", "can"], "🥫"),
    (["avacado", "avocado", "guacamole"], "🥑"),
    ([
        "fish",
        "salmon",
        "tuna",
        "cod",
        "tilapia",
        "hilsa",
        "catfish",
        "herring",
        "sardines",
        "anchovies",
        "mackerel",
        "trout",
        "bass",
        "flounder",
        "sole",
        "halibut",
        "swordfish",
        "grouper",
        "snapper",
        "plaice",
        "bream",
        "sole",
        "pollock",
        "haddock",
        "plaice",
        "shark",
        "seafood",
        "whiting",
        "scampi",
        "skate",
        "sardine",
        "carp",
        "caviar",
        ], "🐟"),
    (["agar"], "🧫"),
    (["yam", "sweet potato"], "🍠"),
    (["pear"], "🍐"),
    (["salt"], "🧂"),
    (["tea"], "🫖"),
    (["wine"], "🍷"),
    (["milk", "yoghurt"], "🥛"),
    (["beer", "lager", "ale", "cider"], "🍺"),
    (["meat"], "🥩"),
    (["juice"], "🧃"),
    (["frozen", "ice"], "🧊"),
    (["butter", "margarine", "fat", "spread"], "🧈"),
    (["roll"], "🍞"),
    ([""], "🍛"),
]

def get_emoji(name):
    for words, emoji in emoji_rules:
        if any(word.lower() in name.lower() for word in words):
            return emoji

print("display_name,emoji")
with open("assets/names.txt") as f:
    for name in f:
        print(f"\"{name.strip()}\",{get_emoji(name)}")

